### ISSUE TITLE
Can't using config file

### ISSUE THREAD

**Issue by Ilav1** [Mydayyy/pbcli#19]
Hi, 

Maybe there is a bug using config file. 

## Situation

pbcli is stored in `/etc/pbcli/`

`echo 'TestPaste' | /etc/pbcli/pbcli --host https://privatebin.net/ --burn` is working fine. 

Now I want to use the config file.
I created the config in `/etc/pbcli/ ('/etc/pbcli/config')` and add the following lines:

```
--host=https://privatebin.net/
--burn
```

Now the comand should work without `--host https://privatebin.net/ --burn`

`echo 'TestPaste' | /etc/pbcli/pbcli` does not work.

Output:

```
#echo 'test' | /etc/pbcli/pbcli
              error: The following required arguments were not provided:
    <URL>

USAGE:
    pbcli <URL>

For more information try --help
```

`echo 'TestPaste' | /etc/pbcli/pbcli --debug` does not work too.

Output:

```
#echo 'test' | /etc/pbcli/pbcli --debug
              error: The following required arguments were not provided:
    <URL>

USAGE:
    pbcli <URL>

For more information try --help
```

`echo 'TestPaste' | /etc/pbcli/pbcli --host https://privatebin.net/ --burn --debug` is working fine.

The debug report is using the config `/etc/pbcli/config`

```
# echo 'test' | /etc/pbcli/pbcli --host https://privatebin.net/ --burn --debug
DEBUG pbcli::config: PBCLI_CONFIG_PATH not set
DEBUG pbcli::config: looking for config at /root/.config/pbcli/config
DEBUG pbcli::config: looking for config at /etc/pbcli/config
DEBUG pbcli::config: using config /etc/pbcli/config
DEBUG reqwest::connect: starting new connection: https://privatebin.net/
DEBUG hyper_util::client::legacy::connect::dns: resolving host="privatebin.net"
DEBUG hyper_util::client::legacy::connect::http: connecting to [2001:1620:2057:1:4902::7]:443
DEBUG hyper_util::client::legacy::connect::http: connected to [2001:1620:2057:1:4902::7]:443
DEBUG hyper_util::client::legacy::pool: pooling idle connection for ("https", privatebin.net)
https://privatebin.net/?f50d5e0825430de6#8TzwbEyCa3AztCBErt37tYmi8YJ3r48uTUvmVuFRRbSi
```

Now I set `PBCLI_CONFIG_PATH=/etc/pbcli/config`.

`echo 'TestPaste' | /etc/pbcli/pbcli --debug` does not work.

Output:
```
#echo 'test' | /etc/pbcli/pbcli --debug
              error: The following required arguments were not provided:
    <URL>

USAGE:
    pbcli <URL>

For more information try --help
```

`echo 'TestPaste' | /etc/pbcli/pbcli --host https://privatebin.net/ --burn --debug` is working fine.

The debug report is using the config `/etc/pbcli/config` again

```
# echo 'test' | /etc/pbcli/pbcli --host https://privatebin.net/ --burn --debug --no-default-config
DEBUG pbcli::config: using config pointed to by PBCLI_CONFIG_PATH
DEBUG pbcli::config: using config /etc/pbcli/config
DEBUG reqwest::connect: starting new connection: https://privatebin.net/
DEBUG hyper_util::client::legacy::connect::dns: resolving host="privatebin.net"
DEBUG hyper_util::client::legacy::connect::http: connecting to [2001:1620:2057:1:4902::7]:443
DEBUG hyper_util::client::legacy::connect::http: connected to [2001:1620:2057:1:4902::7]:443
DEBUG hyper_util::client::legacy::pool: pooling idle connection for ("https", privatebin.net)
https://privatebin.net/?068f39ac53387327#AXaJt1RWQHWJ5oEjLabrjHRaZGxvVSEczzhpG9FQoByW
```
When using the config file with following lines, it's also not possible to use the config file

```
--host https://privatebin.net/
--burn
```
# System
Ubuntu 24.04
pbcli 2.5.0

Please let me know if more information is needed.

**Comment by Mydayyy** [comment]
Greetings,

I identified the issue and I am working on a fix. 

Best Regards
Mydayyy

**Comment by Mydayyy** [comment]
Greetings,

the fix has been released as v2.5.1 on github, AUR and on crates. Please let me know if this works for you and I will proceed to close this issue.

Best Regards
Mydayyy

**Comment by Ilav1** [comment]
Wow, thank you very much for your work 🥇 

pbcli version 2.5.1 is now working for me.

**Comment by ww7** [comment]
Hi! 
On macOS `PBCLI_CONFIG_PATH` not searching at `$HOME/.config/pbcli/config`, but it is common location for configs.

```
❯ echo test | ./target/release/pbcli --debug
DEBUG pbcli::config: PBCLI_CONFIG_PATH not set
DEBUG pbcli::config: looking for config at /Users/ww7/Library/Application Support/eu.mydayyy.pbcli/config
DEBUG pbcli::config: looking for config at /etc/pbcli/config
DEBUG pbcli::config: no config found
error: The following required arguments were not provided:
```

It's easy to solve, but would be fine to include it as default one.

Also, any chance to have keep commented lines at config? It currently trying to parse `#` or `//` lines.

**Comment by Mydayyy** [comment]
Greetings,

thank you for the notice regarding the mac issue. I will try to check that.

Regarding the skipping lines starting with `#` or `//`: This should be fairly easy to implement. I will create an issue tracking that feature and try to get it done this weekend.


Best Regards
Mydayyy

**Comment by Mydayyy** [comment]
> Hi! On macOS `PBCLI_CONFIG_PATH` not searching at `$HOME/.config/pbcli/config`, but it is common location for configs.
> 
> ```
> ❯ echo test | ./target/release/pbcli --debug
> DEBUG pbcli::config: PBCLI_CONFIG_PATH not set
> DEBUG pbcli::config: looking for config at /Users/ww7/Library/Application Support/eu.mydayyy.pbcli/config
> DEBUG pbcli::config: looking for config at /etc/pbcli/config
> DEBUG pbcli::config: no config found
> error: The following required arguments were not provided:
> ```
> 
> It's easy to solve, but would be fine to include it as default one.
> 
> Also, any chance to have keep commented lines at config? It currently trying to parse `#` or `//` lines.

Greetings,

Would you be able to provide an example config where you tried to comment out using `#`? This should already be implemented and working, so it might be a bug.

Best Regards
Mydayyy

**Comment by ww7** [comment]
Hi!

Great, yes, `#` already works.

But if new line before any text it errored:
```
❯ echo test | pbcli
error: Found argument '' which wasn't expected, or isn't valid in this context

USAGE:
    pbcli [OPTIONS] [URL]

For more information try --help
```

with e.g.:
```
--host=https://test.work/bin/
--expire=1month

# --burn
```
