### ISSUE TITLE
Should this application be published on Privatebin's client list?

### ISSUE THREAD

**Issue by nain-F49FF806** [Mydayyy/pbcli#8]
Privatebin project has a wiki page listing [third party clients](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients). 

Perhaps this project should also be on there?

**Comment by Mydayyy** [comment]
Greetings,

thats a good Idea. I'll look into how one can apply there.

Best Regards
Mydayyy

**Comment by Mydayyy** [comment]
PBCLI is now listed!

Best Regards
Mydayyy
